services:
  db:
    image: postgres:13.10
    restart: unless-stopped
    env_file: ./.env
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  backend:
    image: davoos999/taski_backend:latest
    restart: unless-stopped
    env_file: ./.env
    depends_on:
      - db
    volumes:
      - static_volume:/app/collected_static/
      - media_volume:/app/media/

  frontend:
    image: davoos999/taski_frontend:latest
    volumes:
       - static_volume:/app/build/

  gateway:
    image: davoos999/taski_gateway:latest
    restart: unless-stopped
    env_file: ./.env
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
    volumes:
      - static_volume:/staticfiles

volumes:
  postgres_data:
  static_volume:
  media_volume: