volumes:
  pg_data:
  static_volume:
  media_volume:
  django_static_volume:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  backend:
    image: ${DOCKER_USERNAME}/kittygram_backend:latest
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - django_static_volume:/app/collected_static
      - media_volume:/app/media
    command: "gunicorn kittygram_backend.wsgi:application --bind 0.0.0.0:8000 --workers 3"
    restart: unless-stopped

  frontend:
    image: ${DOCKER_USERNAME}/kittygram_frontend:latest
    env_file: .env
    command: cp -r /app/build/. /frontend_static/ && tail -f /dev/null
    volumes:
      - static_volume:/frontend_static
    restart: unless-stopped

  gateway:
    image: ${DOCKER_USERNAME}/kittygram_gateway:latest
    env_file: .env
    ports:
      - "9000:80"
    depends_on:
      - backend
      - frontend
    volumes:
      - static_volume:/usr/share/nginx/html
      - django_static_volume:/collected_static
      - media_volume:/media
    restart: unless-stopped