services:
  db:
    image: postgres:13.10
    restart: unless-stopped
    env_file: ./.env
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  backend:
    image: davoos999/taski_backend:latest
    restart: unless-stopped
    env_file: ./.env
    depends_on:
      - db
    volumes:
      - static_volume:/staticfiles
      - media_volume:/app/media/

  frontend:
    image: davoos999/taski_frontend:latest


  gateway:
    image: davoos999/taski_gateway:latest
    restart: unless-stopped
    env_file: ./.env
    ports:
      - "8001:80"
    depends_on:
      - backend
      - frontend
    volumes:
      - static_volume:/staticfiles
      - ./ssl_certs:/etc/letsencrypt:ro

volumes:
  postgres_data:
  static_volume:
  media_volume: