name: Coping docker-compose.production.yml
on:
  workflow_dispatch:

jobs:
  deploy_yml:
    runs-on: ubuntu-latest
    steps:
      - name: copy docker-compose.production.yml via scp
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          source: README.md
          target: taski
